name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: Test, Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test -Psecret="$SPLITMATE_API_SECRET" -Papi_url="$SPLITMATE_API_URL" -Pgoogle_recaptcha_key="$GOOGLE_RECAPTCHA_KEY" --stacktrace
        env:
          SPLITMATE_API_SECRET: ${{ secrets.SPLITMATE_API_SECRET }}
          SPLITMATE_API_URL: ${{ secrets.SPLITMATE_API_URL }}
          GOOGLE_RECAPTCHA_KEY: ${{ secrets.GOOGLE_RECAPTCHA_KEY }}
      - name: Build debug APK
        run: bash ./gradlew assembleDebug -Psecret="$SPLITMATE_API_SECRET" -Papi_url="$SPLITMATE_API_URL" -Pgoogle_recaptcha_key="$GOOGLE_RECAPTCHA_KEY" --stacktrace
        env:
          SPLITMATE_API_SECRET: ${{ secrets.SPLITMATE_API_SECRET }}
          SPLITMATE_API_URL: ${{ secrets.SPLITMATE_API_URL }}
          GOOGLE_RECAPTCHA_KEY: ${{ secrets.GOOGLE_RECAPTCHA_KEY }}
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk